CREATE TYPE [qan].[IMatRecords] AS TABLE (
    [WW]                           NVARCHAR (10)  NULL,
    [SSD_Id]                       NVARCHAR (100) NULL,
    [Design_Id]                    NVARCHAR (50)  NULL,
    [Scode]                        NVARCHAR (50)  NULL,
    [Cell_Revision]                NVARCHAR (50)  NULL,
    [Major_Probe_Program_Revision] NVARCHAR (50)  NULL,
    [Probe_Revision]               NVARCHAR (50)  NULL,
    [Burn_Tape_Revision]           NVARCHAR (50)  NULL,
    [Custom_Testing_Required]      NVARCHAR (50)  NULL,
    [Custom_Testing_Required2]     NVARCHAR (50)  NULL,
    [Product_Grade]                NVARCHAR (100) NULL,
    [Prb_Conv_Id]                  NVARCHAR (100) NULL,
    [Fab_Conv_Id]                  NVARCHAR (100) NULL,
    [Fab_Excr_Id]                  NVARCHAR (100) NULL,
    [Media_Type]                   NVARCHAR (100) NULL,
    [Media_IPN]                    NVARCHAR (50)  NULL,
    [Device_Name]                  NVARCHAR (100) NULL,
    [Reticle_Wave_Id]              NVARCHAR (100) NULL,
    [Fab_Facility]                 NVARCHAR (100) NULL,
    [Create_Date]                  DATETIME       NULL,
    [Latest]                       NVARCHAR (10)  NULL,
    [File_Type]                    NVARCHAR (10)  NULL);

