CREATE TYPE [qan].[IOsatPasVersionRecordsImport] AS TABLE
(
    [RecordNumber]           INT           NOT NULL,
    [ProductGroup]           VARCHAR (500) NULL,
    [Project]                VARCHAR (500) NULL,
    [IntelProdName]          VARCHAR (500) NULL,
    [IntelLevel1PartNumber]  VARCHAR (500) NULL,
    [Line1TopSideMarking]    VARCHAR (500) NULL,
    [CopyrightYear]          VARCHAR (500) NULL,
    [SpecNumberField]        VARCHAR (500) NULL,
    [MaterialMasterField]    VARCHAR (500) NULL,
    [MaxQtyPerMedia]         VARCHAR (500) NULL,
    [Media]                  VARCHAR (500) NULL,
    [RoHsCompliant]          VARCHAR (500) NULL,
    [LotNo]                  VARCHAR (500) NULL,
    [FullMediaReqd]          VARCHAR (500) NULL,
    [SupplierPartNumber]     VARCHAR (500) NULL,
    [IntelMaterialPn]        VARCHAR (500) NULL,
    [TestUpi]                VARCHAR (500) NULL,
    [PgTierAndSpeedInfo]     VARCHAR (500) NULL,
    [AssyUpi]                VARCHAR (500) NULL,
    [DeviceName]             VARCHAR (500) NULL,
    [Mpp]                    VARCHAR (500) NULL,
    [SortUpi]                VARCHAR (500) NULL,
    [ReclaimUpi]             VARCHAR (500) NULL,
    [ReclaimMm]              VARCHAR (500) NULL,
    [ProductNaming]          VARCHAR (500) NULL,
    [TwoDidApproved]         VARCHAR (500) NULL,
    [TwoDidStartedWw]        VARCHAR (500) NULL,
    [Did]                    VARCHAR (500) NULL,
    [Group]                  VARCHAR (500) NULL,
    [Note]                   VARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([RecordNumber] ASC)
);
