CREATE VIEW [stage].[VSpeedPCodeItems]
AS  SELECT
		  [ItemId]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'BATTERY_HAZMAT_COMPLIANCE_CD') AS [BatteryHazmatComplianceCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'EPM_ID') AS [ExternalProductId]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'LEAD_FREE_PROCESS_COMPATIBLE') AS [PbFreeCompatible]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MARKET_CODE_NAME') AS [MarketCodeName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-BRANDED') AS [BrandedProductIndicator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-BUS-ARCH') AS [BusArchitecture]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-CODE-NAME') AS [DieCodeName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-CPU-SPEED') AS [CpuProcessorSpeed]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-CUST-CUSTOMER') AS [CustomerCustomProduct]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-CUSTOM-IND') AS [CustomIndicator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-ENCRY-CODE') AS [EncryptionCodeName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-ENCRYPT') AS [Encryption]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-FORM-FACT') AS [FormFactor]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-FTO-AFS') AS [FtoAllocFreeStock]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-INCORP') AS [RoyaltyReceivable]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-INTEL-INSIDE') AS [IntelInsideIndicator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-ITEM-MARKET-NAME') AS [ItemMarketName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-MEM1-AMT') AS [MemoryAmount1]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-MEM1-TYPE') AS [MemoryType1]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-MEM2-AMT') AS [MemoryAmount2]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-MEM2-TYPE') AS [MemoryType2]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-PLAN-SYS') AS [PlanningSystem]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-PROD-CAT-BD') AS [BdCategoryType]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-PROD-VISIBILITY') AS [ProductVisibility]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-ROYALTY') AS [RoyaltyPayable]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-SHIP-MED') AS [ShipmentMedia]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-SOS-DEFAULT') AS [SosDefault]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-SPEC-CODE') AS [SpecCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-SPEC-NUMBER') AS [SpecSequentialNumber]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-TRADEMARK') AS [TrademarkName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MODEL_STRING_NAME') AS [ModelStringName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'NAND_LITHOGRAPHY_THKNS_TEXT') AS [NandLithographyThknsText]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'OLD_MATERIAL_NBR') AS [OldMaterialNbr]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS_BITS_PER_CELL') AS [BitsPerCell]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS_LEAD_FREE') AS [PbFree]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS_VERTICAL_SEGMENT') AS [VerticalSegment]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'UNDERFILL_IND') AS [UnderfillInd]
	FROM [stage].[ItemDetailV2] WITH (NOLOCK) WHERE [ItemClassNm] = 'BD' AND [CommodityCd] = '0301'
