CREATE VIEW [stage].[VSpeedDesignItems]
AS  SELECT
		  [ItemId]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'CONNECTOR_DESIGNATOR') AS [ConnectorDesignatorCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'DESIGNED_FUNCTION_CODE') AS [DesignedFunctionCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'DIE_ARCHT_CD') AS [DieArchitectureCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'FAB_DESIGNATOR_CODE') AS [FabCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'FAB_PROCESS') AS [FabProcess]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'LRP_ESTIMATED_CACHE_QUANTITY') AS [LrpEstimatedCacheQuantity]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'LRP_ESTIMATED_CACHE_UOM_CODE') AS [LrpEstimatedCacheUomCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-CODE-NAME') AS [DieCodeName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MM-MEM1-TYPE') AS [MemoryType1]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'NOMEN_PROGRAM_LEVEL_CODE') AS [NomenclatureProgramLevelCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'NOMEN_PROGRAM_SCOPE_CODE') AS [NomenclatureProgramScopeCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'OLD_MATERIAL_NBR') AS [OldMaterialNbr]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PLN_IGNR_IND') AS [PlanningIgnoredIndicator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PRODUCT_LINE') AS [ProductLine]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS_DOT_PROCESS') AS [FabDotProcess]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-DENSITY') AS [Density]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-DENSITY-UOM') AS [DensityUom]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-MFG-DEVICE') AS [MfgDevice]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-MFG-STAGE') AS [MfgStage]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-REV') AS [Rev]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'PS-STEP') AS [InternalStep]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'REQUEST_DATE') AS [RequestDate]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'SUBASSY_PROD_ENGNR_CD') AS [SubassyProdEngnrCd]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'WAFER-SIZE') AS [WaferSize]
	FROM [stage].[ItemDetailV2] WITH (NOLOCK) WHERE [ItemClassNm] = 'UPI_FAB' AND [BusinessUnitNm] = 'NAND_NAND'
