CREATE VIEW [stage].[VSpeedIcFlashItems]
AS  SELECT
		  [ItemId]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'BACKSIDE-MARK-CODE') AS [BacksideMarkCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'DENSITY_UOM') AS [DensityUnitOfMeasure]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'ECC-IND') AS [EccIndicator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'IC-PACKAGE-TYPE') AS [IcPackageType]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'IC-PIN-COUNT') AS [ICPinCount]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'INTEL-FLASH') AS [IntelFlash]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM_DENSITY') AS [MemoryDensity]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-ADDL-INFO') AS [MemoryAdditionalInfo]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-ASSY-TYPE') AS [MemoryAssyType]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-BLANK-PROG') AS [MemoryBlankProg]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-DEVICE-NAME') AS [MemoryDeviceName]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEMORY_CHANNEL_WIDTH_COUNT_CD') AS [MemoryChannelWidthCount]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEMORY-TYPE') AS [MemoryType]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-PLATFORM') AS [MemoryPlatform]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-SIZE') AS [MemorySize]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-SPEED') AS [MemorySpeed]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-SPEED-UOM') AS [MemorySpeedUom]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MEM-VOLTAGE') AS [MemoryVoltage]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'MFG-PKG-DESIG') AS [ManufPackageDesignator]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'REVISION-CODE') AS [RevisionCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'SPEC-CODE') AS [SpecCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'SPEC-TYPE') AS [SpecType]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'STEPPING-CODE') AS [SteppingCode]
		, [stage].[GetItemCharacteristicValue]([ItemId], 'TEMPERATURE_GRADE_DSC') AS [TemperatureGrade]
	FROM [stage].[ItemDetailV2] WITH (NOLOCK) WHERE [ItemDsc] LIKE 'IC,FLASH,%'
