-- =============================================
-- Author:		jakemurx
-- Create date: 2021-03-11 16:41:39.180
-- Description:	Get Lot Ship Snapshot data by scenario Id
-- EXEC [qan].[GetLotShipSnapshot] 'jakemurx', 10
-- =============================================
CREATE PROCEDURE [qan].[GetLotShipSnapshot] 
	-- Add the parameters for the stored procedure here
	@UserId varchar(25), 
	@Id int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT [Version]
		  ,[id]
		  ,[location_type]
		  ,[way_bill]
		  ,[mm_number]
		  ,[description]
		  ,[to_facility]
		  ,[invoice]
		  ,[delivery_note]
		  ,[intel_box]
		  ,[unit_qty]
		  ,[po]
		  ,[intel_upi]
		  ,[design_id]
		  ,[device]
		  ,[number_of_die_in_pkg]
		  ,[probe_program_rev]
		  ,[major_probe_prog_rev]
		  ,[fabrication_facility]
		  ,[app_restriction]
		  ,[apo_number]
		  ,[die_qty]
		  ,[custom_tested]
		  ,[intel_reclaim]
		  ,[alternate_speed_sort]
		  ,[ate_tape_revision]
		  ,[burn_experiment]
		  ,[burn_flow]
		  ,[burn_tape_revision]
		  ,[wafer_qty]
		  ,[custom_testing_reqd]
		  ,[ddp_ineligible]
		  ,[disallow_merging]
		  ,[eng_master_version]
		  ,[fab_excr_id]
		  ,[future_hold_location]
		  ,[hdp_ineligible]
		  ,[hold_for_whom]
		  ,[hold_lot]
		  ,[hold_notes]
		  ,[hold_reason]
		  ,[hot_lot_priority]
		  ,[intel_ship_pass1_qty]
		  ,[intel_ship_pass2_qty]
		  ,[intel_ship_pass3_qty]
		  ,[intel_ship_pass4_qty]
		  ,[inventory_location]
		  ,[lot_has_been_marked]
		  ,[lot_has_rejects]
		  ,[lot_id]
		  ,[marketing_speed]
		  ,[non_shippable]
		  ,[num_array_decks]
		  ,[odp_ineligible]
		  ,[planned_laser_scribe]
		  ,[planned_test_site]
		  ,[product_grade_sorted]
		  ,[prod_grade_sort_reqd]
		  ,[product_grade]
		  ,[qa_asm_conv_hold]
		  ,[qa_asm_excr_hold]
		  ,[qa_asm_swr_hold]
		  ,[qa_disposition_hold]
		  ,[qa_fab_conv_hold]
		  ,[qa_fab_excr_hold]
		  ,[qa_fab_swr_hold]
		  ,[qa_prb_conv_hold]
		  ,[qa_prb_excr_hold]
		  ,[qa_reticle_wave_hold]
		  ,[qa_work_request_desc]
		  ,[qdp_ineligible]
		  ,[test_data_reqd]
		  ,[prb_conv_id]
		  ,[num_io_channels]
		  ,[reticle_wave_id]
		  ,[cell_revision]
		  ,[cmos_revision]
		  ,[cold_final_reqd]
		  ,[excr_containment]
		  ,[lead_count]
		  ,[num_flash_ce_pins]
		  ,[country_of_assembly]
		  ,[last_updated_datetime]
		  ,[last_tracked_source]
		  ,[load_file_datetime]
		  ,[current_location]
		  ,[shipment_date]
		  ,[shipping_label_lot]
		  ,[fab_conv_id]
		  ,[unqualified]
		  ,[elec_special_test]
		  ,[rma_lot]
		  ,[cibr_lot_number]
		  ,[intel_ship_pass5_qty]
		  ,[intel_ship_pass6_qty]
	  FROM [qan].[LotShipSnapshots]
	WHERE [Version] = @Id
END