CREATE TABLE [qan].[OdmComparisonLotDisposition] (
    [Comp_Id]                         INT            NULL,
    [SubConName]                      NVARCHAR (50)  NULL,
    [InventoryLocation]               NVARCHAR (50)  NULL,
    [MMNumber]                        NVARCHAR (50)  NULL,
    [LocationType]                    NVARCHAR (50)  NULL,
    [Category]                        NVARCHAR (50)  NULL,
    [SLot]                            NVARCHAR (50)  NULL,
    [SCode]                           NVARCHAR (50)  NULL,
    [MediaIPN]                        NVARCHAR (50)  NULL,
    [PorMajorProbeProgramRevision]    NVARCHAR (50)  NULL,
    [ActualMajorProbeProgramRevision] NVARCHAR (50)  NULL,
    [PorBurnTapeRevision]             NVARCHAR (50)  NULL,
    [ActualBurnTapeRevision]          NVARCHAR (50)  NULL,
    [PorCellRevision]                 NVARCHAR (50)  NULL,
    [ActualCellRevision]              NVARCHAR (50)  NULL,
    [PorCustomTestingRequired]        NVARCHAR (50)  NULL,
    [ActualCustomTestingRequired]     NVARCHAR (50)  NULL,
    [PorFabConvId]                    NVARCHAR (50)  NULL,
    [ActualFabConvId]                 NVARCHAR (50)  NULL,
    [PorFabExcrId]                    NVARCHAR (50)  NULL,
    [ActualFabExcrId]                 NVARCHAR (50)  NULL,
    [PorProductGrade]                 NVARCHAR (50)  NULL,
    [ActualProductGrade]              NVARCHAR (50)  NULL,
    [PorReticleWaveId]                NVARCHAR (50)  NULL,
    [ActualReticleWaveId]             NVARCHAR (50)  NULL,
    [PorFabFacility]                  NVARCHAR (50)  NULL,
    [ActualFabFacility]               NVARCHAR (50)  NULL,
    [ReasonId]                        INT            NULL,
    [Notes]                           NVARCHAR (MAX) NULL,
    [IsExcluded]                      BIT            NULL,
    [Latest]                          NVARCHAR (10)  NULL
);

